name: Metrics
on:
  workflow_dispatch: # Disabled automatic schedule and push triggers, manual run only
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 3D Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-isometric.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Zainul342
          base: "" 
          config_timezone: Asia/Jakarta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - name: Languages Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Zainul342
          base: "" 
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, shell, php
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 5
